services:

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "${MONGO_PORT}:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: kuldeepofficial/test-backend:latest
    platform: linux/amd64
    container_name: test-backend
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"

    environment:
      PORT: ${BACKEND_INTERNAL_PORT}
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin

    depends_on:
      - mongodb


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: kuldeepofficial/test-frontend:latest
    platform: linux/amd64
    container_name: test-frontend
    restart: unless-stopped

    ports:
      - "${FRONTEND_PORT}:3000"

    environment:
      VITE_API_URL: http://localhost:${BACKEND_PORT}/api

    depends_on:
      - backend


volumes:
  mongodb_data:
