
services:

  mongo:
    image: mongo:4.4.6 
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - test
    restart: unless-stopped

  backend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kuldeepofficial/test-backend:latest
    container_name: test-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kuldeepofficial/test-frontend:latest
    container_name: test-frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  mongo-data:

networks:
  test:
    driver: bridge
